import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

/*

// este es el preconfigurador del modelo que seleccione se copia el codigo para nuestro proyecto y se obtiene el modelo lista para usar
https://github.com/pmndrs/gltfjsx
// 
// */

export function Citygreen(props) {
    const { nodes, materials } = useGLTF('textures_citypart/scene.gltf')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.637}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI, 0, -Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-46.013, 0, 19.917]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-20.013, 0, 45.917]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_13.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-20.022, -0.015, -45.97]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_15.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_16.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-0.022, -0.015, -45.97]} rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_18.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_19.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-0.05, -0.015, -19.97]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_22.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-0.05, -0.015, 20.03]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_25.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.95, -0.015, 20.03]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_27.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_28.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.95, -0.015, 0.03]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_31.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.95, -0.015, -19.97]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_33.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_34.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-20.05, -0.015, -19.97]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_37.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-20.05, -0.015, 0.03]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_39.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_40.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-20.05, -0.015, 20.03]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_42.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_43.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-46.013, 0, -0.083]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_45.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_46.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-46.013, 0, -20.083]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_48.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_49.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.978, -0.015, -45.97]} rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_51.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_52.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-0.013, 0, 45.917]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_54.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_55.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.987, 0, 45.927]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_57.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_58.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[19.878, 0, -19.984]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_60.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_61.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[45.987, 0, -20.083]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_63.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_64.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-46.022, -0.015, -45.97]} rotation={[0, Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_66.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_67.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[45.978, -0.015, -45.97]} rotation={[0, -Math.PI / 2, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_69.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_70.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[45.727, 0, 45.984]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_72.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_73.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-46.013, 0, 45.917]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_75.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_76.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[45.909, 0, 19.917]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_78.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_79.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[45.909, 0, -0.083]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_81.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_82.geometry}
                            material={materials.mat_level1_main}
                        />
                    </group>
                    <group position={[-48.513, 0, 1.398]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_84.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_85.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_86.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-49.868, 0, 47.659]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_88.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_89.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_90.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-46.475, 0, -19.728]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_92.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_93.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_94.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-47.981, 0.324, -45.252]} rotation={[0, 1.557, 0]} scale={1.626}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_96.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_97.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-46.341, 0, 21.063]} rotation={[0, -0.013, 0]} scale={1.539}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_99.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_100.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-0.028, 0.293, -42.391]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_102.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_103.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-0.028, 0.293, -48.342]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_105.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_106.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-43.218, 0, -2.195]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_108.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_109.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_110.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-42.792, 0, 48.955]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_112.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_113.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_114.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-44.729, 0, 43.74]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_116.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_117.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_118.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[20.003, 0, 46.52]} rotation={[0, -0.013, 0]} scale={0.933}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_120.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_121.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_122.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-21.689, 0.359, 43.826]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_124.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_125.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_126.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-22.217, 0.058, 48.7]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_128.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_129.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_130.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-16.675, 0.359, 44.025]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_132.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_133.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_134.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-16.719, 0.058, 48.788]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_136.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_137.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_138.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[18.979, 0, -46.215]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_140.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_141.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[42.62, 0.295, 47.89]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_143.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_144.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_145.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[49.696, 0.295, 49.186]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_147.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_148.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_149.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[47.758, 0.295, 43.971]} rotation={[Math.PI, -1.557, Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_151.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_152.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_153.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[-1.073, 0.213, 46.413]} rotation={[0, -0.013, 0]} scale={1.539}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_155.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_156.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[46.261, 0, -46.165]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_158.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_159.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_160.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[43.409, 0.212, 1.398]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_162.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_163.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_164.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[45.581, 0.233, 21.063]} rotation={[0, -0.013, 0]} scale={1.539}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_166.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_167.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[48.703, 0.212, -2.195]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_169.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_170.geometry}
                            material={materials.mat_level1_second}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_171.geometry}
                            material={materials.mat_building_03_detail}
                        />
                    </group>
                    <group position={[0, 0, -1.85]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_173.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_174.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[0, 0, 3.116]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_176.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_177.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[18.517, 0.282, -39.682]} rotation={[0, -0.013, 0]} scale={1.568}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_179.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_180.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group
                        position={[45.249, 0.302, -19.61]}
                        rotation={[-Math.PI, 0.013, -Math.PI]}
                        scale={1.653}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_182.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_183.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-19.338, 0, 2.5]} rotation={[0, -0.013, 0]} scale={1.28}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_211.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_212.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[19.253, 0, 19.62]} rotation={[0, -0.013, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_214.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_215.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[18.7, 0, -19.731]} rotation={[-Math.PI, 0.013, -Math.PI]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_217.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_218.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[0, 0, -19.843]} rotation={[0, -0.013, 0]} scale={1.216}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_220.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_221.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-20.436, 0, 19.597]} rotation={[0, -0.013, 0]} scale={1.343}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_223.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_224.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[19.525, 0, -1.269]} rotation={[0, -0.013, 0]} scale={1.291}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_226.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_227.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group
                        position={[-20.003, 0, -20.328]}
                        rotation={[-Math.PI, 0.013, -Math.PI]}
                        scale={0.889}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_229.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_230.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-0.397, 0, 18.82]} rotation={[0, -0.013, 0]} scale={1.277}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_232.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_233.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-18.944, 0, -43.58]} rotation={[0, -0.013, 0]} scale={0.644}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_235.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_236.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group
                        position={[-21.187, 0, -47.677]}
                        rotation={[-Math.PI, 0.013, -Math.PI]}
                        scale={0.644}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_238.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_239.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <group position={[-19.338, 0, -4.157]} rotation={[0, -0.013, 0]} scale={1.28}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_241.geometry}
                            material={materials.mat_level1_main}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_242.geometry}
                            material={materials.mat_level1_second}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_10.geometry}
                        material={materials.mat_level1_second}
                        scale={0.953}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_185.geometry}
                        material={materials.material_0}
                        position={[26.906, 0, 33.011]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_187.geometry}
                        material={materials.material_0}
                        position={[32.906, 0, 33.011]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_189.geometry}
                        material={materials.material_0}
                        position={[-33.094, 0, 33.011]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_191.geometry}
                        material={materials.material_0}
                        position={[32.906, 0, -32.989]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_193.geometry}
                        material={materials.material_0}
                        position={[38.866, 0, -32.989]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_195.geometry}
                        material={materials.material_0}
                        position={[-33.093, 0, -32.989]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_197.geometry}
                        material={materials.material_0}
                        position={[-39.094, 0, 33.011]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_199.geometry}
                        material={materials.material_0}
                        position={[-33.094, 0, 39.011]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_201.geometry}
                        material={materials.material_0}
                        position={[-33.023, 0, -39.107]}
                        rotation={[0, -Math.PI / 2, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_203.geometry}
                        material={materials.material_0}
                        position={[-39.023, 0, -32.978]}
                        rotation={[0, -Math.PI / 2, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_205.geometry}
                        material={materials.material_0}
                        position={[32.891, 0, -38.943]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_207.geometry}
                        material={materials.material_0}
                        position={[32.607, 0, 39.011]}
                        rotation={[0, -Math.PI / 2, 0]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_209.geometry}
                        material={materials.material_0}
                        position={[38.607, 0, 33.011]}
                        rotation={[0, -Math.PI / 2, 0]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('textures_citypart/scene.gltf')
