/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import {
    useGLTF,

    useAnimations
} from '@react-three/drei'


export default function Modelwomen(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-taning/model.gltf')
    const { actions, names } = useAnimations(animations, group)
    console.log(names);
    //activacion de animacion del modelo 3D
    useEffect(() => {
        actions[names[0]].reset().fadeIn(0.5).play();
        
    }, []);
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[0.12, -0.06, -0.04,]} scale={0.15} >
                <primitive object={nodes.root} />
                <skinnedMesh geometry={nodes.Femme.geometry} material={materials['color_main.004']} skeleton={nodes.Femme.skeleton} />
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-taning/model.gltf')