/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Modelhuman(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')
    const { actions, names } = useAnimations(animations, group)
    console.log(names);
    //activacion de animacion del modelo 3D
    useEffect(()=>{
        actions[names[0]].reset().fadeIn(0.5).play();
        actions[names[2]].reset().fadeIn(0.5).play();
    },[]);


    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={1.91} >
                <primitive object={nodes.root} />
                <skinnedMesh geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/druid/model.gltf')




