/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import {
    useGLTF,

    useAnimations
} from '@react-three/drei'


export default function Modeloold(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf')
    const { actions, names } = useAnimations(animations, group)
    console.log(names);
    //activacion de animacion del modelo 3D
    useEffect(() => {
        actions[names[0]].reset().fadeIn(0.5).play();

    }, []);
    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={0.15} >
                <primitive object={nodes.root} />
                <skinnedMesh geometry={nodes.Vieux.geometry} material={materials['color_main.001']} skeleton={nodes.Vieux.skeleton} />
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf')