/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect,useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
export default function Modelomono(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/young-korrigan/model.gltf')
    const { actions,names } = useAnimations(animations, group)
    
    console.log(names);
    //activacion de animacion del modelo 3D
    useEffect(()=>{
        actions[names[1]].reset().fadeIn(8).play();
        
    },[]);


    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[0, 1.03, 0,]} scale={0.15} >
                <primitive object={nodes.root} />
                <skinnedMesh geometry={nodes.Jeune.geometry} material={materials['color_main.003']} skeleton={nodes.Jeune.skeleton} />
            </group>

        </group>
    )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/young-korrigan/model.gltf')