/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {  useFrame } from '@react-three/fiber'
export default function Model(props) {
  const { nodes, materials } = useGLTF('../public/scene.gltf')
  const meshRef = useRef()
  
  useFrame((state, delta) => (meshRef.current.rotation.y += delta/10))  
  return (
    <group ref={meshRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={10} />
    </group>
  )
}

useGLTF.preload('../public/scene.gltf')
